Booking_Hotel/Models/data/menu.cs
namespace Booking_Hotel.Models.data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("menu")]
    public partial class menu
    {
        public int id { get; set; }

        [StringLength(50)]
        public string title { get; set; }

        [StringLength(50)]
        public string link { get; set; }

        public bool? IsActive { get; set; }

        public int? menu_order { get; set; }
    }
}

Booking_Hotel/Areas/Admin/Controllers/HomeController.cs
using Booking_Hotel.Models.data;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Booking_Hotel.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        BookingDataModels myObj = new BookingDataModels();
        // GET: Admin/Home
        public class ch
        {
            public int country;
            public int value;
        }
        public ActionResult Index()
        {
            TempData["CountRooms"] = myObj.rooms.Count();
            TempData["CountBlogs"] = myObj.blogs.Count();
            TempData["CountMails"] = myObj.mails.Count();
            TempData["CountRents"] = myObj.rents.Count();
            var mo = DateTime.Now.Month;
            var item = from i in myObj.rents
                       where i.date.Value.Month == mo
                       group i.id_rent by i.date.Value.Day into h
                       select new ch()
                       {
                           country = h.Key,
                           value = h.Count(),
                       };
            return View(item);
        }
        public ActionResult Mail()
        {
            var item = myObj.mails.Where(i => i.IsRead == false).OrderByDescending(i => i.ContactId).ToList();
            ViewBag.Mail = item.Count();
            return PartialView("_Mail", item);
        }
        public ActionResult AllMail()
        {
            var item = myObj.mails.OrderByDescending(i => i.ContactId).ToList();
            return View("AllMail", item);
        }
        public ActionResult DeleteMail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mail mail = myObj.mails.Find(id);
            if (mail == null)
            {
                return HttpNotFound();
            }
            myObj.mails.Remove(mail);
            myObj.SaveChanges();
            ThongBao("Xoá thành công!!!", "success");
            return RedirectToAction("AllMail");
        }

        public ActionResult MailDetail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mail type = myObj.mails.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            type.IsRead = true;
            myObj.SaveChanges();
            return View("Mail", type);
        }
        public ActionResult ContactAdmin()
        {
            var item = myObj.contacts.Single();
            return View("ContactAdmin", item);
        }
        public ActionResult EditContact(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contact contact = myObj.contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Admin/contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditContact([Bind(Include = "id,address,phone,email,facebook_link")] contact contact)
        {
            if (ModelState.IsValid)
            {
                myObj.Entry(contact).State = EntityState.Modified;
                myObj.SaveChanges();
                return RedirectToAction("ContactAdmin");
            }
            return View(contact);
        }
    }
}

Booking_Hotel/Areas/Admin/Controllers/MenusController.cs
using Booking_Hotel.Models.data;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Booking_Hotel.Areas.Admin.Controllers
{
    public class MenusController : BaseController
    {
        private BookingDataModels db = new BookingDataModels();

        // GET: Admin/menus
        public ActionResult Index()
        {
            return View(db.menus.ToList());
        }

        // GET: Admin/menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            menu menu = db.menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // GET: Admin/menus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,link,IsActive,menu_order")] menu menu)
        {
            if (ModelState.IsValid)
            {
                db.menus.Add(menu);
                db.SaveChanges();
                ThongBao("Thêm thành công!!!", "success");

                return RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: Admin/menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            menu menu = db.menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Admin/menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,link,IsActive,menu_order")] menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                ThongBao("Sửa thành công!!!", "success");

                return RedirectToAction("Index");
            }
            return View(menu);
        }

        // GET: Admin/menus/Delete/5

        // POST: Admin/menus/Delete/5
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            menu menu = db.menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            db.menus.Remove(menu);
            db.SaveChanges();
            ThongBao("Xoá thành công!!!", "success");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult changeView(int? id)
        {
            menu menu = db.menus.Find(id);
            menu.IsActive = !menu.IsActive;
            db.SaveChanges();
            return Json(new
            {
                status = menu.IsActive
            });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Booking_Hotel/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Booking_Hotel.Models.data;

namespace Booking_Hotel.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
        BookingDataModels myObj = new BookingDataModels();

        public ActionResult Rate()
        {
            var items = myObj.rates.Where(i => (bool)i.IsActive).ToList();
            return PartialView("Rate", items);
        }
    }
}

Booking_Hotel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Booking_Hotel.Models.data;

namespace Booking_Hotel.Controllers
{
    public class HomeController : Controller
    {
        BookingDataModels myObj = new BookingDataModels();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Menu()
        {
            var item = myObj.menus.Where(i => (bool)i.IsActive).OrderBy(j => j.menu_order).ToList();
            return PartialView("Menu", item);
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Layout_Contact()
        {
            var items = myObj.contacts.Take(1);
            return PartialView("Layout_Contact", items);
        }
        public ActionResult DkDv()
        {
            return View("DK_DV");
        }
        public ActionResult faqs()
        {
            return View("FAQs");
        }
    }
}

Booking_Hotel/Controllers/RoomsController.cs
using Microsoft.Ajax.Utilities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Booking_Hotel.Models.data;
using System.Data.Entity;

namespace Booking_Hotel.Controllers
{
    public class RoomsController : Controller
    {
        BookingDataModels myObj = new BookingDataModels();

        public ActionResult Index(string Name, int Type = 0)
        {
            var typees = from i in myObj.types select i;
            ViewBag.Type = new SelectList(typees, "id_type", "type1");
            var names = myObj.rooms.Include(j => j.types);
            if (!string.IsNullOrEmpty(Name))
            {
                names = names.Where(i => i.name.Contains(Name));
            }
            if (Type != 0)
            {
                names = names.Where(j => j.id_type == Type);
            }
            return View(names.ToList());
        }
        public ActionResult RoomList_Home()
        {
            var items = myObj.rooms.Include(j => j.types);
            items = items.Where(i => (bool)i.IsActive).Where(j => (bool)j.IsHot);
            return PartialView("RoomList", items.ToList());
        }
        public ActionResult Details(int? idx)
        {
            if (idx == null) return HttpNotFound();
            else
            {
                var items = myObj.rooms.Find(idx);
                return View("Detail", items);
            }
        }
        /*Comment*/
        public ActionResult CommentRoom(int id)
        {
            var items = myObj.Comment_Room.Where(i => i.id_room == id).ToList();
            ViewBag.room = items.Count();
            return PartialView("CommentRoom", items);
        }
        [HttpPost]
        public ActionResult AddCommentRoom(int id, string name, string content)
        {
            Comment_Room newcmt_room = new Comment_Room();
            newcmt_room.id_room = id;
            newcmt_room.name_cmt = name;
            newcmt_room.cmt_room = content;
            newcmt_room.date_cmt = DateTime.Now;
            myObj.Comment_Room.Add(newcmt_room);
            myObj.SaveChanges();
            return Json(new { status = true });
        }
    }
}

Booking_Hotel/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="hero-wrap ftco-degree-bg" style="background-image: url('../../content/images/hotelhub.jpg'); " data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text justify-content-start align-items-center justify-content-center">
            <div class="col-lg-8 ftco-animate">
                <div class="text w-100 text-center mb-md-5 pb-md-5">
                    <h1 class="mb-4">Nhanh Chóng &amp; Đơn Giản Để Thuê Phòng </h1>
                    <p style="font-size: 18px;">Web đặt phòng với giá cả đi đôi cùng chất lượng.</p>
                    <marquee direction="right" scrollamount="5">
                        @*<a href="" class="icon-wrap d-flex align-items-center mt-4 justify-content-center">
                            <div class="icon d-flex align-items-center justify-content-center">
                                <i class="fas fa-motorcycle fa-2x"></i>
                            </div>
                        </a>*@
                    </marquee>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section ftco-no-pt bg-light">
    <div class="container">
        <div class="row no-gutters">
            <div class="col-md-12	featured-top">
                <div class="col-md-8 d-flex align-items-center">
                    <div class="services-wrap rounded-right w-100">
                        <h3 class="heading-section mb-4">Hãy để việc đặt phòng trở nên dễ dàng hơn</h3>
                        <div class="row d-flex mb-4">
                            <div class="col-md-4 d-flex align-self-stretch ftco-animate">
                                <div class="services w-100 text-center">
                                    <div class="icon d-flex align-items-center justify-content-center"><span class="flaticon-route"></span></div>
                                    <div class="text w-100">
                                        <h3 class="heading mb-2">Xác định khách sạn cần đến</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 d-flex align-self-stretch ftco-animate">
                                <div class="services w-100 text-center">
                                    <div class="icon d-flex align-items-center justify-content-center"><span class="flaticon-handshake"></span></div>
                                    <div class="text w-100">
                                        <h3 class="heading mb-2">Chọn phòng phù hợp</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 d-flex align-self-stretch ftco-animate">
                                <div class="services w-100 text-center">
                                    <div class="icon d-flex align-items-center justify-content-center"><span class="flaticon-backpack"></span></div>
                                    <div class="text w-100">
                                        <h3 class="heading mb-2">Đặt phòng với chúng tôi</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p><a href="~/Rooms" class="btn btn-primary py-3 px-4">Thuê Phòng Ngay</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section ftco-no-pt bg-light">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 heading-section text-center ftco-animate mb-5">
                <span class="subheading"><i>Lựa chựa của bạn</i></span>
                <h2 class="mb-2">Mẫu phòng nổi bật</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="carousel-car owl-carousel">
                    @{Html.RenderAction("RoomList_Home", "Rooms");}
                </div>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section ftco-about">
    <div class="container">
        <div class="row no-gutters">
            <div class="col-md-6 p-md-5 img img-2 d-flex justify-content-center align-items-center" style="background-image: url(../../content/images/bg_2.png); ">
            </div>
            <div class="col-md-6 wrap-about ftco-animate">
                <div class="heading-section heading-section-white pl-md-5">
                    <span class="subheading">Về chúng tôi</span>
                    <h2 class="mb-4">Chào mừng bạn đến với dịch vụ Booking Hotel</h2>

                    <p style="text-align:justify">Với nhiều danh lam thắng cảnh, di tích lịch sử, các điểm vui chơi, giải trí, Booking Hotel sẽ đưa bạn đến trong kỳ nghỉ lễ.</p>
                    <p style="text-align:justify">Hiện nay, do nhu cầu du lịch phiêu lưu, khám phá tăng cao, các địa điểm du lịch nghỉ dưỡng được nhiều bạn lựa chọn. Bởi tính chất đặc thù của hình thức du lịch này mà booking onnline trở thành phương tiện phù hợp, được ưu tiên sử dụng. Từ đó dịch vụ Booking Hotel ra đời và ngày một phổ biến.</p>
                    <p><a href="~/Rooms" class="btn btn-primary py-3 px-4">Tìm phòng </a></p>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="ftco-section testimony-section bg-light">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7 text-center heading-section ftco-animate">
                <span class="subheading">Cảm nhận khách hàng khi thuê</span>
                <h2 class="mb-3">Nhận xét tích cực</h2>
            </div>
        </div>
        <div class="row ftco-animate">
            <div class="col-md-12">
                <div class="carousel-testimony owl-carousel ftco-owl">
                    @{ Html.RenderAction("Rate", "About");}
                </div>
            </div>
        </div>
    </div>
</section>

<section class="ftco-counter ftco-section img bg-light" id="section-counter">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
                <div class="block-18">
                    <div class="text text-border d-flex align-items-center">
                        <strong class="number" data-number="5">0</strong>
                        <span>Năm<br>Phát Triển</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
                <div class="block-18">
                    <div class="text text-border d-flex align-items-center">
                        <strong class="number" data-number="100">0</strong>
                        <span>Tổng số <br>Phòng</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
                <div class="block-18">
                    <div class="text text-border d-flex align-items-center">
                        <strong class="number" data-number="300">0</strong>
                        <span>Khách hàng <br>Thường xuyên</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 justify-content-center counter-wrap ftco-animate">
                <div class="block-18">
                    <div class="text d-flex align-items-center">
                        <strong class="number" data-number="95">0</strong>
                        <span>% <br>Hài lòng</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Booking_Hotel/Views/Home/Menu.cshtml
@foreach (var item in Model)
{
    <li class="nav-item" style="text-transform: uppercase;">
        <a href="@item.link" class="nav-link">@item.title</a>
    </li>
}